python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 21 --model_path pretrained/Img1k-CUB.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 21 --model_path pretrained/Img1k-CUB.pth
python test.py --way 4 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 21 --model_path pretrained/Img1k-CUB.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 22 --model_path pretrained/Img1k-CUB-CD.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 22 --model_path pretrained/Img1k-CUB-CD.pth
python test.py --way 4 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 22 --model_path pretrained/Img1k-CUB-CD.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 23 --model_path pretrained/Img1k-CUB-CD-ES.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 23 --model_path pretrained/Img1k-CUB-CD-ES.pth
python test.py --way 4 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 23 --model_path pretrained/Img1k-CUB-CD-ES.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 24 --model_path pretrained/Img1k-CUB-CD-ES-ISIC.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 24 --model_path pretrained/Img1k-CUB-CD-ES-ISIC.pth
python test.py --way 4 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 24 --model_path pretrained/Img1k-CUB-CD-ES-ISIC.pth