python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 9 --model_path pretrained/Img900-Mini80.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 9 --model_path pretrained/Img900-Mini80.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 9 --model_path pretrained/Img900-Mini80.pth
python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 10 --model_path pretrained/Img900-Mini80-CD.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 10 --model_path pretrained/Img900-Mini80-CD.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 10 --model_path pretrained/Img900-Mini80-CD.pth
python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 11 --model_path pretrained/Img900-Mini80-CD-ES.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 11 --model_path pretrained/Img900-Mini80-CD-ES.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 11 --model_path pretrained/Img900-Mini80-CD-ES.pth
python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 12 --model_path pretrained/Img900-Mini80-CD-ES-ISIC.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 12 --model_path pretrained/Img900-Mini80-CD-ES-ISIC.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 12 --model_path pretrained/Img900-Mini80-CD-ES-ISIC.pth