python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 1 --model_path pretrained/Img900-Mini.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 1 --model_path pretrained/Img900-Mini.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 2 --model_path pretrained/Img900-Mini2.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 2 --model_path pretrained/Img900-Mini2.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 3 --model_path pretrained/Img900-Mini3.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 3 --model_path pretrained/Img900-Mini3.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 4 --model_path pretrained/Img900-Mini4.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 4 --model_path pretrained/Img900-Mini4.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 5 --model_path pretrained/Img900-Mini5.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 5 --model_path pretrained/Img900-Mini5.pth
python test.py --way 4 --shot 5 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 6 --model_path pretrained/Img900-Mini6.pth
python test.py --way 4 --shot 20 --backbone AmdimNet --dataset KidneyStones --cross_ds VincentEstrade --test_epi 200 --gpu $1 --tag 6 --model_path pretrained/Img900-Mini6.pth