python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 28 --model_path pretrained/Img1k-All.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 28 --model_path pretrained/Img1k-All.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 28 --model_path pretrained/Img1k-All.pth
python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 29 --model_path pretrained/Img1k-CUB-All.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 29 --model_path pretrained/Img1k-CUB-All.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 29 --model_path pretrained/Img1k-CUB-All.pth
python test.py --way 5 --shot 5 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 30 --model_path pretrained/Img1k-All_ExcCUB.pth
python test.py --way 5 --shot 20 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 30 --model_path pretrained/Img1k-All_ExcCUB.pth
python test.py --way 5 --shot 50 --backbone AmdimNet --dataset KidneyStones --test_epi 1000 --gpu $1 --tag 30 --model_path pretrained/Img1k-All_ExcCUB.pth