python test_few_shot.py --shot 1 --config ./configs/icn-1shot-7.yaml --gpu 6
python test_few_shot.py --shot 1 --config ./configs/icn-1shot-8.yaml --gpu 6
python test_few_shot.py --shot 1 --config ./configs/icn-1shot-9.yaml --gpu 6
python test_few_shot.py --shot 1 --config ./configs/icn-1shot-10.yaml --gpu 6
python test_few_shot.py --shot 1 --config ./configs/icn-1shot-11.yaml --gpu 6
python test_few_shot.py --shot 1 --config ./configs/icn-1shot-12.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-7.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-8.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-9.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-10.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-11.yaml --gpu 6
python test_few_shot.py --shot 5 --config ./configs/icn-5shot-12.yaml --gpu 6
