python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 1 --k-train 5 --n-train 1 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 1 --k-train 5 --n-train 1 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 1 --k-train 5 --n-train 1 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 1 --k-train 5 --n-train 1 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 1 --k-train 5 --n-train 1 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 5 --k-train 5 --n-train 5 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 5 --k-train 5 --n-train 5 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 5 --k-train 5 --n-train 5 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 5 --k-train 5 --n-train 5 --q-train 15 --gpuid 1
python -m experiments.proto_nets --dataset miniImageNet --k-test 5 --n-test 5 --k-train 5 --n-train 5 --q-train 15 --gpuid 1