dataset: mini-imagenet
dataset_args: {split: test}

icn:
  save_icn_scores: False
  icn_models: 'umap,pca,isomap,kernel_pca,truncated_svd,feature_agg,nmf'
  icn_reduction_set: 'all'
  icn_reduction_type: 'unsupervised'
  icn_multiple_components: True
  icn_n_dims: 6
  icn_original_score: True

load: ./save/meta_mini-imagenet-5shot_meta-baseline-resnet12/max-va.pth
name: test-5shot-exp12